In [33]:
RSV =[18,19,22]
AOA =[1,15,1]

# Student ID (2023-4-0284)
first_set = [2,0,2]
second_set = [2,8,4]


# Define the matrices
matrix_1 = np.array([[18, 19, 22], [1, 15, 1]])
matrix_2 = np.array([[2, 0, 2], [2, 8, 4]])


# Matrix Addition
matrix_3 = matrix_1 + matrix_2


# Scalar Multiplication
matrix_4 = matrix_1 * 2


# Transpose of 2nd Matrix
matrix_5 = matrix_2.T


# Matrix Multiplication (matrix3 [2x3] * matrix5 [3x2] = matrix6 [2x2])
matrix_6 = np.dot(matrix_3, matrix_5)


# Sum of all elements in matrix3
sum_matrix_3 = np.sum(matrix_3)

# Zero Matrix (2x3)
matrix_7 = np.zeros((2, 3), dtype=int)



In [11]:
import numpy as np
print("1st Matrix:\n",matrix_1,
      "\n\n2nd Matrix:\n",matrix_2,
      "\n\n3rd Matrix (Addition):\n",matrix_3,
      "\n\n4th Matrix (Scalar Multiplication):\n",matrix_4,
      "\n\n5th Matrix (Transpose):\n",matrix_5,
      "\n\n6th Matrix (Multiplication):\n",matrix_6,
      "\n\nSum of all elements in 3rd Matrix:\n", sum_matrix_3,
      "\n\n7th Matrix (Zero Matrix):\n",matrix_7) 


1st Matrix:
 [[18 19 22]
 [ 1 15  1]] 

2nd Matrix:
 [[2 0 2]
 [2 8 4]] 

3rd Matrix (Addition):
 [[20 19 24]
 [ 3 23  5]] 

4th Matrix (Scalar Multiplication):
 [[36 38 44]
 [ 2 30  2]] 

5th Matrix (Transpose):
 [[2 2]
 [0 8]
 [2 4]] 

6th Matrix (Multiplication):
 [[ 88 288]
 [ 16 210]] 

Sum of all elements in 3rd Matrix:
 94 

7th Matrix (Zero Matrix):
 [[0 0 0]
 [0 0 0]]
